### ISSUE TITLE
Support InsecureSkipVerify TLS Option (self-signed)

### ISSUE THREAD

**Issue by cognoz** [Linaro/openstack-exporter#4] opened 2019-02-28 11:11 UTC
Hi! 
First of all, thx for your project. 
I get errors like this [pastebin](https://pastebin.com/ipdzvkcY) then hit /metrics endpoint
I have installed os-client-config via pip and made /etc/openstack/clouds.yml with this content:
[clouds.yml](https://pastebin.com/uZfdsCZB)
Can you help me?

**Comment by niedbalski** [comment] 2019-02-28 22:47
Hello @cognoz 

I'll improve the error handling at the metrics gathering to make the cause of any error more evident.

Here is the example template os-client-config that I use:

https://raw.githubusercontent.com/openstack/kolla-ansible/master/ansible/roles/prometheus/templates/clouds.yml.j2

Please check this config and let me know if any directive is missing at yours.

**Comment by hex2dec** [comment] 2019-03-01 00:52
hi, @cognoz can you show me your `clouds.yaml` configuration without sensitive data. Maybe the `auth_url` and `identity_api_version` was mis-configuration.

**Comment by hex2dec** [comment] 2019-03-01 01:11
hi, @cognoz you can add `identity_api_version: 3 ` into your `clouds.yaml` configuration. It use keystone API v2 if you not setting `identity_api_version` to `3`. https://github.com/Linaro/openstack-exporter/blob/24333d5941b765202d0486cd5738e31b0a35e9f4/exporter.go#L75-L79

**Comment by hex2dec** [comment] 2019-03-01 01:22
> Hi!
> First of all, thx for your project.
> I get errors like this [pastebin](https://pastebin.com/ipdzvkcY) then hit /metrics endpoint
> I have installed os-client-config via pip and made /etc/openstack/clouds.yml with this content:
> [clouds.yml](https://pastebin.com/uZfdsCZB)
> Can you help me?

The `openstack-exporter ` project does not depend on [openstack/os-client-config](https://github.com/openstack/os-client-config) python project, it just uses os-client-config configuration structure.

**Comment by niedbalski** [comment] 2019-03-01 23:38
@hex2dec thank you for your input and help!.  @cognoz is there any feedback from you?

**Comment by cognoz** [comment] 2019-03-02 10:07
Thx everyone for your help. 
Do you now how I can enable 'insecure' for this exporter for https endpoints ?
Now I get errors like this https://pastebin.com/JGZ4W4i4
My current clouds.yml https://pastebin.com/infEH3WL
PS. I have already installed certificate on my machine, so, for example, I dont have any problems with https endpoints via curl

**Comment by niedbalski** [comment] 2019-03-04 01:02
Hello @cognoz 

Can you please try with the latest image? docker pull quay.io/niedbalski/openstack-exporter:master

This should be fixed by https://github.com/Linaro/openstack-exporter/commit/5a7d6be71d9ec7eee5897e2a3c577dbfb4c31251 

Please set verify: False at the auth configuration and report back.

Thank you

**Comment by cognoz** [comment] 2019-03-04 09:22
Same problem  
clouds.yml https://pastebin.com/0kcXTfk9
log https://pastebin.com/UBT0nRQH
Tried both version - compiled on host and docker image  (both from master)  
CONTAINER ID        IMAGE                                          COMMAND                  CREATED              STATUS                         PORTS                                                              NAMES
045e9e04b204        quay.io/niedbalski/openstack-exporter:master   "/bin/openstack-expo…"   About a minute ago   Up About a minute

**Comment by niedbalski** [comment] 2019-03-04 23:08
Hello @cognoz 

I've added the InsecureSkipVerify = true option to the TLS settings when verify is equals to False.

Can you please try with the latest image? docker pull quay.io/niedbalski/openstack-exporter:master and report back here?

Thanks!

**Comment by cognoz** [comment] 2019-03-05 07:49
Same errors https://pastebin.com/vJ4ZeFDh
Pulled latest image 
Image sha 
`docker image inspect bfe108064511  | grep sha
        "Id": "sha256:bfe10806451157cfa35fd303ee706b5e2ccf070f7ec8c7ec0b67744fd6b63c06",
            "quay.io/niedbalski/openstack-exporter@sha256:6933e8e27f801ae33df398b2bf265b7df81d4f060e1e0b744c2c43132ac8af7a"  )`

As I remember, I have resolved the same errors with old canonnical exporter via env var
> export REQUESTS_CA_BUNDLE=/PATH/ca.pem

where ca.pem is self-signed bundle which used on HAproxy

**Comment by niedbalski** [comment] 2019-03-05 23:01
@cognoz 

OK, so you have a different CA bundle. I've added the cacert and verify options to the auth settings.  Please try with:
cacert: "--- CA BUNDLE string ---"
verify: false

**Comment by niedbalski** [comment] 2019-03-06 21:10
@cognoz 

I've added the cacert and verify options via commit https://github.com/Linaro/openstack-exporter/commit/3b52817863e6f9950865447c37e72ade6c8d7b3e 

I've also documented the currently available options via https://github.com/Linaro/openstack-exporter#openstack-configuration

Please let me know if this solves your issue and report back.

Thank you.

**Comment by cognoz** [comment] 2019-03-08 09:19
@niedbalski
Ok, I'll try it on sunday, thx!

**Comment by cognoz** [comment] 2019-03-12 17:25
Sorry for long response, 
still, no luck
https://pastebin.com/mdPWyiRG
my clouds.yml 
https://pastebin.com/T1HYEfz2


PS. Also I found that i have warnings in cannonical exporter like that (but still, its works)
https://pastebin.com/Yf6Z124r
It uses that admin.rc https://pastebin.com/iAvW6XS9   (I can change both internalURL on public or http on https, and it works)

**Comment by niedbalski** [comment] 2019-06-24 13:48
Feel free to open a new issue if this problem still occurs at (https://github.com/openstack-exporter/openstack-exporter)

**Closed as completed by niedbalski** 2019-06-24 13:48 UTC
